"""initial migration

Revision ID: a2f5925d67d8
Revises: 
Create Date: 2026-07-06 11:22:31.657926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f5925d67d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_maintenance_visits_id'), table_name='maintenance_visits')
    op.drop_table('maintenance_visits')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_service_records_id'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_ownership_costs_id'), table_name='ownership_costs')
    op.drop_table('ownership_costs')
    op.drop_index(op.f('ix_mileage_history_id'), table_name='mileage_history')
    op.drop_table('mileage_history')
    op.drop_index(op.f('ix_maintenance_schedule_id'), table_name='maintenance_schedule')
    op.drop_table('maintenance_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('service_type', sa.VARCHAR(), nullable=True),
    sa.Column('interval_miles', sa.INTEGER(), nullable=True),
    sa.Column('interval_months', sa.INTEGER(), nullable=True),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('uses_health_indicator', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedule_id'), 'maintenance_schedule', ['id'], unique=False)
    op.create_table('mileage_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('entry_date', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mileage_history_id'), 'mileage_history', ['id'], unique=False)
    op.create_table('ownership_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('cost_date', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('vendor', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_costs_id'), 'ownership_costs', ['id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('service_type', sa.VARCHAR(), nullable=True),
    sa.Column('service_date', sa.VARCHAR(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('next_service_mileage', sa.INTEGER(), nullable=True),
    sa.Column('next_service_date', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_id'), 'service_records', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nickname', sa.VARCHAR(), nullable=True),
    sa.Column('vin', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('make', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('trim', sa.VARCHAR(), nullable=True),
    sa.Column('current_mileage', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('maintenance_visits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('visit_date', sa.VARCHAR(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('vendor', sa.VARCHAR(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_visits_id'), 'maintenance_visits', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('document_type', sa.VARCHAR(), nullable=True),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('upload_date', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('archived', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('event_date', sa.VARCHAR(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###
