# alembic revision identifiers, used by Alembic.
# revision = 'cebf4a8a0a07'

"""Add maintenance visit link

Revision ID: cebf4a8a0a07
Revises: a2f5925d67d8
Create Date: 2026-07-06 12:00:09.483170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebf4a8a0a07'
down_revision: Union[str, Sequence[str], None] = 'a2f5925d67d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
