"""add archived to service record

Revision ID: f04ad7bf94c1
Revises: 039c20d841db
Create Date: 2026-07-25 14:14:20.909227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04ad7bf94c1'
down_revision: Union[str, Sequence[str], None] = '039c20d841db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_column(
        'service_records',
        'archived'
    )

    # ### end Alembic commands ###
