"""add service record fields

Revision ID: 3d559bdf6bc4
Revises: 77897c909403
Create Date: 2026-07-25 10:21:47.663438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d559bdf6bc4'
down_revision: Union[str, Sequence[str], None] = '77897c909403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:

    op.add_column(
        'service_records',
        sa.Column(
            'primary_reason',
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        'service_records',
        sa.Column(
            'parts_used',
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        'service_records',
        sa.Column(
            'additional_services',
            sa.String(),
            nullable=True
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('service_records', 'additional_services')
    op.drop_column('service_records', 'parts_used')
    op.drop_column('service_records', 'primary_reason')
    # ### end Alembic commands ###
