"""Add service status

Revision ID: 60c65b35da71
Revises: cebf4a8a0a07
Create Date: 2026-07-07 08:40:09.132286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c65b35da71'
down_revision: Union[str, Sequence[str], None] = 'cebf4a8a0a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('service_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'service_status')
    # ### end Alembic commands ###
